apiVersion: v1
kind: Service
metadata:
  name: gsl-transportation-service
  namespace: gsl
spec:
  selector:
    app: gsl-transportation
  ports:
    - protocol: "TCP"
      port: 8080
      targetPort: 8080
  type: LoadBalancer