version: '3.5'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:    
      POSTGRES_PASSWORD: postgres
      POSTGRES_MULTIPLE_DATABASES: "orderdb,freightdb,collectiondb,transportationdb,deliverydb,partnershipdb,customerdb"
    volumes:
       - ./postgres:/docker-entrypoint-initdb.d