##Compile image
FROM gradle:7.5.1-jdk11-alpine AS build
WORKDIR /workspace/app

COPY build.gradle.kts settings.gradle.kts ./

RUN gradle clean build --no-daemon > /dev/null 2>&1 || true

COPY src src

RUN gradle clean build --no-daemon


#Binary image
FROM openjdk:11-jre-slim
VOLUME /tmp

ARG DEPENDENCY=/workspace/app/build/libs

ENV PORT=8080
ENV KAFKA_BOOTSTRAP_SERVERS=192.168.0.2:9092
ENV RABBITMQ_PORT=5672
ENV RABBITMQ_HOST=192.168.0.2
ENV RABBITMQ_USER=rabbitmq
ENV RABBITMQ_PASS=rabbitmq
ENV DATABASE_HOST=192.168.0.2
ENV DATABASE_PORT=5432
ENV DATABASE_USER=gsl
ENV DATABASE_PASS=gsl
ENV EVENTSOURCING_FREIGHT_COMMAND=gsl.command.freight
ENV EVENTSOURCING_FREIGHT_EVENT=gsl.event.freight
ENV EVENTSOURCING_FREIGHT_DOCUMENT=gsl.document.freight
ENV EVENTSOURCING_ORDER_EVENT=gsl.event.order
ENV EVENTSOURCING_ORDER_COMMAND=gsl.command.order
ENV EVENTSOURCING_ORDER_DOCUMENT=gsl.document.order
ENV EVENTSOURCING_CUSTOMER_EVENT=gsl.event.customer
ENV EVENTSOURCING_CUSTOMER_COMMAND=gsl.command.customer
ENV EVENTSOURCING_CUSTOMER_DOCUMENT=gsl.document.customer

COPY --from=build ${DEPENDENCY} /app/lib
ENTRYPOINT ["java","-jar","/app/lib/app.jar"]