server:
  port: ${PORT:8081}

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      client-id: configure-me_client-id
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:192.168.0.2:9092}
  rabbitmq:
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:192.168.0.2}
    username: ${RABBITMQ_USER:rabbitmq}
    password: ${RABBITMQ_PASS:rabbitmq}
  application:
    name: order
  h2:
    console:
      settings:
        web-allow-others: 'false'
        trace: 'false'
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:order-db;Mode=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  sql:
    init:
      platform: h2
      continue-on-error: 'true'
  data:
    web:
      pageable:
        size-parameter: size
        prefix: ''
        one-indexed-parameters: 'false'
        page-parameter: page
        default-page-size: '20'
        qualifier-delimiter: _
        max-page-size: '2000'


outbox:
  storage:
    polling:
      frequencyInMillis: 1000

eventsourcing:
  platform: kafka
  messaging:
    order:
      event: ${EVENTSOURCING_ORDER_EVENT:gsl.event.order}
      command: ${EVENTSOURCING_ORDER_COMMAND:gsl.command.order}
    customer:
      event: ${EVENTSOURCING_CUSTOMER_EVENT:gsl.event.customer}
      command: ${EVENTSOURCING_CUSTOMER_COMMAND:gsl.command.customer}
    delivery:
      event: ${EVENTSOURCING_DELIVERY_EVENT:gsl.event.delivery}
      command: ${EVENTSOURCING_DELIVERY_COMMAND:gsl.command.delivery}
    collector:
      event: ${EVENTSOURCING_COLLECTOR_EVENT:gsl.event.collector}
      command: ${EVENTSOURCING_COLLECTOR_COMMAND:gsl.command.collector}
    partners:
      event: ${EVENTSOURCING_PARTNERS_EVENT:gsl.event.partners}
      command: ${EVENTSOURCING_PARTNERS_COMMAND:gsl.command.partners}
    routing:
      event: ${EVENTSOURCING_ROUTING_EVENT:gsl.event.routing}
      command: ${EVENTSOURCING_ROUTING_COMMAND:gsl.command.routing}
    freight:
      command: ${EVENTSOURCING_FREIGHT_COMMAND:gsl.command.freight}
      event: ${EVENTSOURCING_FREIGHT_EVENT:gsl.event.freight}





