server:
  port: ${PORT:8081}

spring:
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: ${spring.application.name}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      client-id: configure-me_client-id
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:192.168.0.2:9092}
  rabbitmq:
    port: ${RABBITMQ_PORT:5672}
    host: ${RABBITMQ_HOST:192.168.0.2}
    username: ${RABBITMQ_USER:rabbitmq}
    password: ${RABBITMQ_PASS:rabbitmq}
  application:
    name: order
  h2:
    console:
      settings:
        web-allow-others: 'false'
        trace: 'false'
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:order-db;Mode=Oracle;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
  sql:
    init:
      platform: h2
      continue-on-error: 'true'

eventsourcing:
  platform: kafka
  kafka:
    group-id: ${spring.application.name}
    topics:
      order: order
      freight: freight
  amqp:
    queues:
      event:
        name: ${EVENTSOURCING_QUEUE_EVENT:gsl.events}
      command:
        name: ${EVENTSOURCING_QUEUE_COMMAND:gsl.commands}




