apiVersion: apps/v1
kind: Deployment
metadata:
  name: gsl-module
  namespace: gsl
spec:
  selector:
    matchLabels:
      app: gsl-module
  replicas: 2
  template:
    metadata:
      labels:
        app: gsl-module
    spec:
      containers:
        - name: gsl-module-unit
          image: gsl/xpto-service:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080