apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: gsl
  labels:
    name: webserver

spec:
  containers:
    - name: webserver
      image: gsl/order
      ports:
        - containerPort: 8080