apiVersion: v1
kind: Service
metadata:
  name: gsl-order-service
  namespace: gsl
spec:
  selector:
    app: gsl-order
  ports:
    - protocol: "TCP"
      port: 8761
      targetPort: 8080
  type: LoadBalancer