apiVersion: v1
kind: Service
metadata:
  name: gsl-delivery-service
  namespace: gsl
spec:
  selector:
    app: gsl-delivery
  ports:
    - protocol: "TCP"
      port: 8765
      targetPort: 8080
  type: LoadBalancer