apiVersion: v1
kind: Service
metadata:
  name: gsl-freight-service
  namespace: gsl
spec:
  selector:
    app: gsl-freight
  ports:
    - protocol: "TCP"
      port: 8762
      targetPort: 8080
  type: LoadBalancer